name: github pages continuous deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      # - name: setup node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "10.x"
      # -
      - name: build
        run: npm run build
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: client/build
